# Generated by Django 4.2.8 on 2023-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
